# Generated by Django 5.2.8 on 2025-11-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("clients", "0002_client_created_by_alter_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="clients.client",
                verbose_name="client",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="location"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
    ]
