# Generated by Django 5.2.8 on 2025-11-15 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("client_created", "Client Created"),
                            ("client_updated", "Client Updated"),
                            ("appointment_created", "Appointment Created"),
                            ("appointment_updated", "Appointment Updated"),
                            ("appointment_completed", "Appointment Completed"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                        ],
                        max_length=25,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_date", models.DateField(auto_now_add=True)),
                ("total_clients", models.IntegerField(default=0)),
                ("total_appointments", models.IntegerField(default=0)),
                ("upcoming_appointments", models.IntegerField(default=0)),
                ("completed_appointments", models.IntegerField(default=0)),
                ("cancelled_appointments", models.IntegerField(default=0)),
                ("new_clients_this_month", models.IntegerField(default=0)),
                (
                    "revenue_this_month",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-stat_date"],
                "unique_together": {("user", "stat_date")},
            },
        ),
    ]
